# CI workflow temporarily disabled
# To re-enable, restore the original workflow content
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # All jobs are disabled
  test:
    runs-on: ubuntu-latest
    steps:
      - name: CI Temporarily Disabled
        run: echo "CI is temporarily disabled. To re-enable, restore the original workflow content."

# Original workflow content (commented out)
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         julia-version: ['1.9', '1.10']
#     steps:
#       - uses: actions/checkout@v3
#       
#       - uses: julia-actions/setup-julia@v1
#         with:
#           version: ${{ matrix.julia-version }}
#           
#       - uses: julia-actions/julia-buildpkg@v1
#       
#       - uses: julia-actions/julia-runtest@v1
#       
#       - uses: julia-actions/julia-processcoverage@v1
#         with:
#           coverage: true
#
#   coverage:
#     runs-on: ubuntu-latest
#     needs: test
#     steps:
#       - uses: actions/checkout@v3
#       
#       - uses: julia-actions/setup-julia@v1
#         with:
#           version: '1.10'
#       
#       - uses: julia-actions/julia-runtest@v1
#       
#       - uses: julia-actions/julia-processcoverage@v1
#         with:
#           coverage: true
#           
#       - uses: codecov/codecov-action@v3
#         with:
#           file: ./lcov.info
#           flags: unittests
#           name: Julia Tests
#           fail_ci_if_error: true
